---
name: Sample project build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository 1
        uses: actions/checkout@v4
        id: checkout1
      
      - name: Run a one-line script
        run: |  
          owner=$(echo "${{ github.repository }}" | cut -d'/' -f1)
          repo=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          echo "Hello Cats config files: $owner/$repo"
